package com.syswave.forms.miempresa;

import com.syswave.entidades.miempresa.AreaPrecio;
import com.syswave.entidades.miempresa.Valor;
import com.syswave.forms.databinding.ValorComboBoxModel;
import com.syswave.swing.renders.POJOListCellRenderer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author sis2
 */
public class JAreaPrecioDetailView extends javax.swing.JInternalFrame
{
   private IAreaPrecioMediator parent;
   private boolean esNuevo, construidoArbol;
   private AreaPrecio elementoActual;
   private ValorComboBoxModel bsTipoPrecioRender;
   
   //---------------------------------------------------------------------
   /**
    * Creates new form JAreaPrecioDetailView
    * @param owner
    */
   public JAreaPrecioDetailView(IAreaPrecioMediator owner)
   {
      initAttributes();
      initComponents();
      initEvents();
      parent = owner;
   }
   
   private void initAttributes ()
   {
       bsTipoPrecioRender = new ValorComboBoxModel();
   }
   
   //---------------------------------------------------------------------
   private void initEvents()
   {
      ActionListener actionListenerManager
                     = new ActionListener()
      {
         @Override
         public void actionPerformed(ActionEvent evt)
         {
            finish_actionPerformed(evt);
         }
      };
      
      
      jbAceptar.addActionListener(actionListenerManager);
      jbCancelar.addActionListener(actionListenerManager);
   }

   
   //---------------------------------------------------------------------
   private void finish_actionPerformed (ActionEvent evt)
   {
      Object sender = evt.getSource();
      
      if (sender == jbAceptar)
      {
         if (readElement(elementoActual))
         {
            if (esNuevo)
               parent.onAcceptNewElement(elementoActual);

            else 
            {
               elementoActual.setModified();
               parent.onAcceptModifyElement(elementoActual);
            }
            
            close();
         }
      }
      
      else
         close ();
   }
   
   //---------------------------------------------------------------------
   public void prepareForNew ()
   {
      elementoActual = new AreaPrecio();
      esNuevo = true;
      bsTipoPrecioRender.setData(parent.obtenerTipoPrecios());
      this.setTitle("Nueva localidad");
   }
   
   //---------------------------------------------------------------------
   public void prepareForModify (AreaPrecio elemento)
   {
      this.elementoActual = elemento;
      esNuevo = false;
      bsTipoPrecioRender.setData(parent.obtenerTipoPrecios());
      this.setTitle(String.format("Modificando %s", elemento.getDescripcion()));
      writeElement(elemento);
   }
   
   //---------------------------------------------------------------------
   public void writeElement (AreaPrecio elemento)
   {
      jtfNombre.setText(elemento.getDescripcion());
      jcbTIpoPrecio.setSelectedItem(bsTipoPrecioRender.getElementAt(bsTipoPrecioRender.indexOfValue(elemento.getEsTipo())));
      jchkCostoDirecto.setSelected(elemento.esCostoInDirecto());
      jchkCostoVariable.setSelected(elemento.esCostoVariable());
   }
   
   //---------------------------------------------------------------------
   private boolean readElement (AreaPrecio elemento)
   {
      boolean resultado= false;
      String mensaje = "";
      
      if (!jtfNombre.getText().isEmpty() /*&& !jtfSiglas.getText().isEmpty()*/)
      {
         resultado = true;
         elemento.setDescripcion(jtfNombre.getText());
         elemento.setEsTipo((int) bsTipoPrecioRender.getSelectedValue());
         elemento.setCostoDirecto(!jchkCostoDirecto.isSelected());
         elemento.setEsCostoVariable(jchkCostoVariable.isSelected());
         if (!elemento.isSet())
            elemento.setModified();
      }
      
      else
         mensaje = "Asegurese de proporcionar el nombre";
      
      if (!resultado)
         JOptionPane.showMessageDialog(this, mensaje, "", JOptionPane.PLAIN_MESSAGE);
      
      return resultado;
   }
  
    //---------------------------------------------------------------------
   public void close ()
   {
      this.setVisible(false);
      this.dispose();
   }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jpEncabezado = new javax.swing.JPanel();
        jlbIcono = new javax.swing.JLabel();
        jpAreaMensajes = new java.awt.Panel();
        tpCuerpo = new javax.swing.JTabbedPane();
        jpGeneral = new javax.swing.JPanel();
        jpContenido = new javax.swing.JPanel();
        jlbUsuario = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jlbTIpoPrecio = new javax.swing.JLabel();
        jcbTIpoPrecio = new javax.swing.JComboBox<>();
        jlbCostoDirecto = new javax.swing.JLabel();
        jchkCostoDirecto = new javax.swing.JCheckBox();
        jlbCostoVariable = new javax.swing.JLabel();
        jchkCostoVariable = new javax.swing.JCheckBox();
        jpAcciones = new javax.swing.JPanel();
        jbCancelar = new javax.swing.JButton();
        jbAceptar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jpEncabezado.setBackground(new java.awt.Color(70, 123, 152));
        jpEncabezado.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpEncabezado.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        jlbIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syswave/forms/resources/window.png"))); // NOI18N
        jlbIcono.setAlignmentX(0.5F);
        jlbIcono.setFocusTraversalPolicyProvider(true);
        jlbIcono.setFocusable(false);
        jlbIcono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlbIcono.setIconTextGap(0);
        jlbIcono.setPreferredSize(new java.awt.Dimension(40, 50));
        jlbIcono.setRequestFocusEnabled(false);
        jpEncabezado.add(jlbIcono);

        jpAreaMensajes.setBackground(java.awt.SystemColor.desktop);
        jpAreaMensajes.setLayout(new java.awt.GridLayout(2, 1));
        jpEncabezado.add(jpAreaMensajes);

        getContentPane().add(jpEncabezado, java.awt.BorderLayout.PAGE_START);

        jpContenido.setLayout(new java.awt.GridLayout(4, 2, 2, 2));

        jlbUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbUsuario.setText("Descripción:");
        jlbUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jlbUsuario.setPreferredSize(new java.awt.Dimension(200, 15));
        jpContenido.add(jlbUsuario);

        jtfNombre.setPreferredSize(new java.awt.Dimension(100, 30));
        jpContenido.add(jtfNombre);

        jlbTIpoPrecio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbTIpoPrecio.setText("Tipo:");
        jpContenido.add(jlbTIpoPrecio);

        jcbTIpoPrecio.setModel(bsTipoPrecioRender);
        jcbTIpoPrecio.setRenderer(new POJOListCellRenderer<Valor>());
        jpContenido.add(jcbTIpoPrecio);

        jlbCostoDirecto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbCostoDirecto.setText("Componen otros precios:");
        jpContenido.add(jlbCostoDirecto);
        jlbCostoDirecto.getAccessibleContext().setAccessibleName("Son necesarios para calcular otros precios:");

        jchkCostoDirecto.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jpContenido.add(jchkCostoDirecto);

        jlbCostoVariable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbCostoVariable.setText("Necesitan Analisis de costos:");
        jpContenido.add(jlbCostoVariable);
        jpContenido.add(jchkCostoVariable);

        jpGeneral.add(jpContenido);

        tpCuerpo.addTab("General", jpGeneral);

        getContentPane().add(tpCuerpo, java.awt.BorderLayout.CENTER);

        jpAcciones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syswave/forms/resources/button-cross.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jpAcciones.add(jbCancelar);

        jbAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syswave/forms/resources/button-tick.png"))); // NOI18N
        jbAceptar.setText("Aceptar");
        jpAcciones.add(jbAceptar);

        getContentPane().add(jpAcciones, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JComboBox<Valor> jcbTIpoPrecio;
    private javax.swing.JCheckBox jchkCostoDirecto;
    private javax.swing.JCheckBox jchkCostoVariable;
    private javax.swing.JLabel jlbCostoDirecto;
    private javax.swing.JLabel jlbCostoVariable;
    private javax.swing.JLabel jlbIcono;
    private javax.swing.JLabel jlbTIpoPrecio;
    private javax.swing.JLabel jlbUsuario;
    private javax.swing.JPanel jpAcciones;
    private java.awt.Panel jpAreaMensajes;
    private javax.swing.JPanel jpContenido;
    private javax.swing.JPanel jpEncabezado;
    private javax.swing.JPanel jpGeneral;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTabbedPane tpCuerpo;
    // End of variables declaration//GEN-END:variables
}
