package com.syswave.forms.miempresa;

import com.syswave.entidades.miempresa.ControlAlmacen;
import com.syswave.entidades.miempresa.Mantenimiento;
import com.syswave.entidades.miempresa.Persona;
import com.syswave.entidades.miempresa.Valor;
import com.syswave.forms.databinding.ControlAlmacenesComboBoxModel;
import com.syswave.forms.databinding.PersonasComboBoxModel;
import com.syswave.forms.databinding.ValorComboBoxModel;
import com.syswave.swing.renders.POJOListCellRenderer;
import java.util.Date;

/**
 *
 * @author Gilberto Aaron Jiménez
 */
public class JMantenimientoPDialog extends javax.swing.JDialog
{
    JMantenimientoDataView parents;
    Mantenimiento pElemento;
    private ValorComboBoxModel bsTipoTipoRender;
    private ControlAlmacenesComboBoxModel bsSerieRender;
    private PersonasComboBoxModel bsRsponsableRender;
    
    private boolean ok;

    //--------------------------------------------------------------------
    /**
     * Creates new form JMantenimientoPDialog
     *
     * @param parent
     * @param modal
     * @param owner
     */
    public JMantenimientoPDialog(javax.swing.JFrame parent, boolean modal, JMantenimientoDataView owner)
    {
        
        super(parent, modal);
        
        ok = false;
        
        parents = owner;
        initComponents();
        
        bsTipoTipoRender = new ValorComboBoxModel();
        bsRsponsableRender = new PersonasComboBoxModel();
        bsSerieRender = new ControlAlmacenesComboBoxModel();
        
        bsTipoTipoRender.setData(parents.bsTipoComprobantesEditor.getData());
        bsRsponsableRender.setData(parents.bsResponsablesRender.getData());
        bsSerieRender.setData(parents.bsSerieRender.getData());
        
        jcbTipo.setModel(bsTipoTipoRender);
        jcbResponsable.setModel(bsRsponsableRender);
        jcbSerie.setModel(bsSerieRender);
        jcbTipo.setRenderer(new POJOListCellRenderer<Valor>());
        jcbResponsable.setRenderer(new POJOListCellRenderer<Persona>());
        jcbSerie.setRenderer(new POJOListCellRenderer<ControlAlmacen>());
        
    }
    
    //--------------------------------------------------------------------
    public boolean isOk()
    {
        return ok;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jlbTipo = new javax.swing.JLabel();
        jcbTipo = new javax.swing.JComboBox();
        jlbFolio = new javax.swing.JLabel();
        jtxFolio = new javax.swing.JTextField();
        jlbResponsable = new javax.swing.JLabel();
        jcbResponsable = new javax.swing.JComboBox();
        jlbFecha = new javax.swing.JLabel();
        jdcFechaInicio = new com.toedter.calendar.JDateChooser();
        jlbHasta = new javax.swing.JLabel();
        jdcFechaFin = new com.toedter.calendar.JDateChooser();
        jblSerie = new javax.swing.JLabel();
        jcbSerie = new javax.swing.JComboBox();
        jblActivo = new javax.swing.JLabel();
        jchbActivo = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jbtImprimir = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Parametros de Busqueda");
        setModal(true);

        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 200));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jlbTipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbTipo.setText("Tipo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jlbTipo, gridBagConstraints);

        jcbTipo.setPreferredSize(new java.awt.Dimension(275, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jcbTipo, gridBagConstraints);

        jlbFolio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbFolio.setText("Folio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jlbFolio, gridBagConstraints);

        jtxFolio.setMinimumSize(new java.awt.Dimension(64, 26));
        jtxFolio.setPreferredSize(new java.awt.Dimension(175, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jtxFolio, gridBagConstraints);

        jlbResponsable.setText("Responsable");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jlbResponsable, gridBagConstraints);

        jcbResponsable.setPreferredSize(new java.awt.Dimension(275, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jcbResponsable, gridBagConstraints);

        jlbFecha.setText("Fecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jlbFecha, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(jdcFechaInicio, gridBagConstraints);

        jlbHasta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbHasta.setText("a:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jlbHasta, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(jdcFechaFin, gridBagConstraints);

        jblSerie.setText("Serie");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jblSerie, gridBagConstraints);

        jcbSerie.setPreferredSize(new java.awt.Dimension(275, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jcbSerie, gridBagConstraints);

        jblActivo.setText("Activos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jblActivo, gridBagConstraints);

        jchbActivo.setSelected(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jchbActivo, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setMinimumSize(new java.awt.Dimension(512, 52));
        jPanel2.setPreferredSize(new java.awt.Dimension(433, 66));

        jbtImprimir.setText("Imprimir");
        jbtImprimir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbtImprimirActionPerformed(evt);
            }
        });
        jPanel2.add(jbtImprimir);

        jbtnLimpiar.setText("Limpiar");
        jbtnLimpiar.setToolTipText("");
        jbtnLimpiar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbtnLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnLimpiar);

        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbtCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtCancelar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //--------------------------------------------------------------------
    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtCancelarActionPerformed

    //--------------------------------------------------------------------
    private void jbtImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtImprimirActionPerformed
        
        ok = true;
        this.dispose();
        
    }//GEN-LAST:event_jbtImprimirActionPerformed

    //--------------------------------------------------------------------
    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbtnLimpiarActionPerformed
    {//GEN-HEADEREND:event_jbtnLimpiarActionPerformed
        // TODO add your handling code here:
        jcbTipo.setSelectedIndex(-1);
        jcbResponsable.setSelectedIndex(-1);
        jcbSerie.setSelectedIndex(-1);
        jtxFolio.setText("");
        jdcFechaInicio.setDate(null);
        jdcFechaFin.setDate(null);
        jchbActivo.setSelected(true);
    }//GEN-LAST:event_jbtnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jblActivo;
    private javax.swing.JLabel jblSerie;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtImprimir;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JComboBox jcbResponsable;
    private javax.swing.JComboBox jcbSerie;
    private javax.swing.JComboBox jcbTipo;
    private javax.swing.JCheckBox jchbActivo;
    private com.toedter.calendar.JDateChooser jdcFechaFin;
    private com.toedter.calendar.JDateChooser jdcFechaInicio;
    private javax.swing.JLabel jlbFecha;
    private javax.swing.JLabel jlbFolio;
    private javax.swing.JLabel jlbHasta;
    private javax.swing.JLabel jlbResponsable;
    private javax.swing.JLabel jlbTipo;
    private javax.swing.JTextField jtxFolio;
    // End of variables declaration//GEN-END:variables

    //--------------------------------------------------------------------
    
    void loadDefaults(Mantenimiento elemento)
    {
        
        pElemento = new Mantenimiento();
        
        jcbTipo.setSelectedItem(bsTipoTipoRender.getElementAt(bsTipoTipoRender.indexOfValue(elemento.getEsTipo())));
        jcbSerie.setSelectedIndex(bsSerieRender.indexOfValue(elemento.getIdSerie()));
        jtxFolio.setText(elemento.getFolio());
        jdcFechaInicio.setDate(elemento.getFechaCreacion());
        jdcFechaFin.setDate(elemento.getFechaCreacion());
        jcbResponsable.setSelectedIndex(bsRsponsableRender.indexOfValue(elemento.getIdPersona()));
        jchbActivo.setSelected(elemento.esActivo());
        
    }
    
    void prepareForNew()
    {
        
    }
    
    //--------------------------------------------------------------------
    public int getTipo()
    {
        return bsTipoTipoRender.getCurrent() != null ? bsTipoTipoRender.getCurrent().getId() : -1;        
    }

    //--------------------------------------------------------------------
    public String getFolio()
    {
        return jtxFolio.getText();
    }

    //--------------------------------------------------------------------
    public Date getFechaInicio()
    {
        return jdcFechaInicio.getDate() != null ? jdcFechaInicio.getDate() : Mantenimiento.EMPTY_DATE;        
    }

    //--------------------------------------------------------------------
    public Date getFechaFin()
    {
        return jdcFechaFin.getDate() != null ? jdcFechaFin.getDate() : Mantenimiento.EMPTY_DATE;        
    }
    
    //--------------------------------------------------------------------
    public int getResponsable()
    {
        return bsRsponsableRender.getCurrent() != null ? bsRsponsableRender.getCurrent().getId() : -1;
    }

    //--------------------------------------------------------------------
    public String getSerie()
    {
        return bsSerieRender.getCurrent() != null ? bsSerieRender.getCurrent().getCompositeKey() : "-1,-1";
    }

    //--------------------------------------------------------------------
    public boolean getEstatus()
    {
        return jchbActivo.isSelected();
    }   
}