package com.syswave.forms.miempresa;

import com.syswave.entidades.miempresa.Puesto;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author sis5
 */
public class JPuestoDetailView extends javax.swing.JInternalFrame
{

    Puesto elementoActual;
    boolean esNuevo;
    IPuestoMediator parent;
    
    //---------------------------------------------------------------------
    public JPuestoDetailView(IPuestoMediator owner)
    {
        initComponents();
        initEvents();
        parent = owner;
        esNuevo = true;
        
    }

    //---------------------------------------------------------------------
    private void initEvents()
    {
        ActionListener actionListenerManager
                = new ActionListener()
                {
                    @Override
                    public void actionPerformed(ActionEvent evt)
                    {
                        finish_actionPerformed(evt);
                    }
                };
        
        jbAceptar.addActionListener(actionListenerManager);
        jbCancelar.addActionListener(actionListenerManager);
        
    }
    
    //---------------------------------------------------------------------
    private void finish_actionPerformed(ActionEvent evt)
    {
        Object sender = evt.getSource();
        
        if (sender == jbAceptar)
        {
            if (readElement(elementoActual))
                if (esNuevo)
                {
                    parent.onAcceptNewElement(elementoActual);
                    close();
                }
                else
                {
                    parent.onAcceptModifyElement(elementoActual);
                    close();
                };
        }
        else
            close();
    }

    //---------------------------------------------------------------------
    public void close()
    {
        setVisible(false);
        dispose();
    }
    
    //---------------------------------------------------------------------
    void prepareForNew()
    {
        this.setTitle("Nuevo puesto");
        elementoActual = new Puesto();
    }
    
    void prepareForModify(Puesto elemento)
    {
        this.elementoActual = elemento;
        esNuevo = false;
        this.setTitle("Modificando puesto " + elemento.getNombre().toString());
        writeElement(elemento);
    }
    
    //---------------------------------------------------------------------
    private void writeElement(Puesto elemento)
    {
        jtfNombre.setText(elemento.getNombre());
        jchActivo.setSelected(elemento.isActivo());
    }

    //---------------------------------------------------------------------
    private boolean readElement(Puesto elemento)
    {
        boolean resultado = false;
        
        if (!jtfNombre.getText().equals(""))
        {
            elemento.setNombre(jtfNombre.getText());
            elemento.setActivo(jchActivo.isSelected() ? true : false);
            resultado = true;
        }
        else
            JOptionPane.showMessageDialog(this, "Asegúrese de proporcionar el nombre del puesto.", "", JOptionPane.PLAIN_MESSAGE);
        
        return resultado;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jpEncabezado = new javax.swing.JPanel();
        jlbIcono = new javax.swing.JLabel();
        jpActions = new javax.swing.JPanel();
        jbCancelar = new javax.swing.JButton();
        jbAceptar = new javax.swing.JButton();
        jpBody = new javax.swing.JTabbedPane();
        tabGeneral = new javax.swing.JPanel();
        jpDatos = new javax.swing.JPanel();
        jlbNombre = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jchActivo = new javax.swing.JCheckBox();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jpEncabezado.setBackground(new java.awt.Color(103, 99, 217));

        jlbIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syswave/forms/resources/window.png"))); // NOI18N

        javax.swing.GroupLayout jpEncabezadoLayout = new javax.swing.GroupLayout(jpEncabezado);
        jpEncabezado.setLayout(jpEncabezadoLayout);
        jpEncabezadoLayout.setHorizontalGroup(
            jpEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEncabezadoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jlbIcono)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpEncabezadoLayout.setVerticalGroup(
            jpEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbIcono)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jpEncabezado, java.awt.BorderLayout.NORTH);

        jpActions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syswave/forms/resources/button-cross.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jpActions.add(jbCancelar);

        jbAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syswave/forms/resources/button-tick.png"))); // NOI18N
        jbAceptar.setText("Aceptar");
        jpActions.add(jbAceptar);

        getContentPane().add(jpActions, java.awt.BorderLayout.SOUTH);

        tabGeneral.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jpDatos.setPreferredSize(new java.awt.Dimension(380, 91));
        jpDatos.setLayout(new java.awt.GridLayout(3, 2, 5, 5));

        jlbNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbNombre.setText("Nombre:");
        jpDatos.add(jlbNombre);
        jpDatos.add(jtfNombre);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Activo:");
        jpDatos.add(jLabel3);
        jpDatos.add(jchActivo);

        tabGeneral.add(jpDatos);

        jpBody.addTab("General", tabGeneral);

        getContentPane().add(jpBody, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 484, 315);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JCheckBox jchActivo;
    private javax.swing.JLabel jlbIcono;
    private javax.swing.JLabel jlbNombre;
    private javax.swing.JPanel jpActions;
    private javax.swing.JTabbedPane jpBody;
    private javax.swing.JPanel jpDatos;
    private javax.swing.JPanel jpEncabezado;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JPanel tabGeneral;
    // End of variables declaration//GEN-END:variables
}
