package com.syswave.forms.miempresa;

import com.syswave.entidades.miempresa.Valor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author sis5
 */
public class JValoresDetailView extends javax.swing.JInternalFrame
{
    private Valor elementoActual;
    private boolean esNuevo;
    private IValorMediator parent;
    private final String default_seccion;
    
    
    public JValoresDetailView(IValorMediator owner, String seccion)
    {
        initComponents();
        initEvents();
        parent = owner;
        esNuevo = true;
        default_seccion = seccion;
    }
    
    //---------------------------------------------------------------------
    private void initEvents()
    {
        ActionListener actionListenerManager
                = new ActionListener()
                {
                    @Override
                    public void actionPerformed(ActionEvent evt)
                    {
                        finish_actionPerformed(evt);
                    }
                };
        
        jbAceptar.addActionListener(actionListenerManager);
        jbCancelar.addActionListener(actionListenerManager);
        
    }
    
    //---------------------------------------------------------------------
    private void finish_actionPerformed(ActionEvent evt)
    {
        Object sender = evt.getSource();
        
        if (sender == jbAceptar)
        {
            if (readElement(elementoActual))
                if (esNuevo)
                {
                    parent.onAcceptNewElement(elementoActual);
                    close();
                }
                else
                {
                    parent.onAcceptModifyElement(elementoActual);
                    close();
                };
        }
        else
            close();
    }

    //---------------------------------------------------------------------
    public void close()
    {
        setVisible(false);
        dispose();
    }
    
    //---------------------------------------------------------------------
    public void prepareForModify(Valor elemento)
    {
        this.elementoActual = elemento;
        esNuevo = false;
        this.setTitle("Modificando " + elemento.getValor() + ", " + elemento.getDescripcion());
        writeElement(elemento);
    }
    
    //---------------------------------------------------------------------
    public void prepareForNew()
    {
        elementoActual = new Valor();
        esNuevo = true;
        this.setTitle("Nuevo");
    }
    
    //---------------------------------------------------------------------
    private void writeElement(Valor elemento)
    {
        jtfValor.setText(elemento.getValor());
        jtfDescripcion.setText(elemento.getDescripcion());
        jcbActivo.setSelected(elemento.esActivo());
    }

    //---------------------------------------------------------------------
    private boolean readElement(Valor elemento)
    {
        boolean resultado = false;
        
        if (!jtfValor.getText().equals(""))
        {
            elemento.setValor(jtfValor.getText());
            elemento.setDescripcion(jtfDescripcion.getText());
            elemento.setActivo(jcbActivo.isSelected());
            elemento.setSeccion(default_seccion);
            //elemento.setFormato(title);
            resultado = true;
        }
        else
            JOptionPane.showMessageDialog(this, "Asegúrese de proporcionar la clave", "", JOptionPane.PLAIN_MESSAGE);
        
        return resultado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jpEncabezado = new javax.swing.JPanel();
        jlbIcono = new javax.swing.JLabel();
        jpActions = new javax.swing.JPanel();
        jbCancelar = new javax.swing.JButton();
        jbAceptar = new javax.swing.JButton();
        jpBody = new javax.swing.JTabbedPane();
        tabGeneral = new javax.swing.JPanel();
        jpDatos = new javax.swing.JPanel();
        jlbValor = new javax.swing.JLabel();
        jtfValor = new javax.swing.JTextField();
        jbDescripcion = new javax.swing.JLabel();
        jtfDescripcion = new javax.swing.JTextField();
        jbActivo = new javax.swing.JLabel();
        jcbActivo = new javax.swing.JCheckBox();

        jLabel1.setText("jLabel1");

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jpEncabezado.setBackground(new java.awt.Color(128, 218, 234));

        jlbIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syswave/forms/resources/window.png"))); // NOI18N

        javax.swing.GroupLayout jpEncabezadoLayout = new javax.swing.GroupLayout(jpEncabezado);
        jpEncabezado.setLayout(jpEncabezadoLayout);
        jpEncabezadoLayout.setHorizontalGroup(
            jpEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEncabezadoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jlbIcono)
                .addContainerGap(428, Short.MAX_VALUE))
        );
        jpEncabezadoLayout.setVerticalGroup(
            jpEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbIcono)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jpEncabezado, java.awt.BorderLayout.NORTH);

        jpActions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syswave/forms/resources/button-cross.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jpActions.add(jbCancelar);

        jbAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syswave/forms/resources/button-tick.png"))); // NOI18N
        jbAceptar.setText("Aceptar");
        jpActions.add(jbAceptar);

        getContentPane().add(jpActions, java.awt.BorderLayout.SOUTH);

        tabGeneral.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jpDatos.setPreferredSize(new java.awt.Dimension(450, 85));
        jpDatos.setLayout(new java.awt.GridLayout(3, 2, 5, 5));

        jlbValor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbValor.setText("* Clave:");
        jpDatos.add(jlbValor);
        jpDatos.add(jtfValor);

        jbDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jbDescripcion.setText("Descripción:");
        jpDatos.add(jbDescripcion);
        jpDatos.add(jtfDescripcion);

        jbActivo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jbActivo.setText("Activo:");
        jpDatos.add(jbActivo);

        jcbActivo.setSelected(true);
        jpDatos.add(jcbActivo);

        tabGeneral.add(jpDatos);

        jpBody.addTab("General", tabGeneral);

        getContentPane().add(jpBody, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 510, 344);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JLabel jbActivo;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JLabel jbDescripcion;
    private javax.swing.JCheckBox jcbActivo;
    private javax.swing.JLabel jlbIcono;
    private javax.swing.JLabel jlbValor;
    private javax.swing.JPanel jpActions;
    private javax.swing.JTabbedPane jpBody;
    private javax.swing.JPanel jpDatos;
    private javax.swing.JPanel jpEncabezado;
    private javax.swing.JTextField jtfDescripcion;
    private javax.swing.JTextField jtfValor;
    private javax.swing.JPanel tabGeneral;
    // End of variables declaration//GEN-END:variables
}
