/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.syswave.swing;

/**
 *
 * @author victor
 */
public class JDerechosInternalFrame extends javax.swing.JInternalFrame
{

   /**
    * Creates new form AboutJInternalFrame
    */
   public JDerechosInternalFrame()
   {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jspInformacion = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jpBanner = new javax.swing.JPanel();
        jlbImagen = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(442, 459));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Este sistema es el producto del esfuerzo de 4 años de planeacion\ny varios meses de trabajo.\nSi te gusta demuestralo apoyando a sus creadores.\n\nVersion: 1.0\nProducto: Tonansis\nProducido por: SYSWAVE TI");
        jspInformacion.setViewportView(jTextArea1);

        getContentPane().add(jspInformacion, java.awt.BorderLayout.CENTER);

        jlbImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syswave/forms/resources/SYSWAVE.png"))); // NOI18N
        jlbImagen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlbImagen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jpBanner.add(jlbImagen);

        getContentPane().add(jpBanner, java.awt.BorderLayout.NORTH);

        setSize(new java.awt.Dimension(452, 449));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jlbImagen;
    private javax.swing.JPanel jpBanner;
    private javax.swing.JScrollPane jspInformacion;
    // End of variables declaration//GEN-END:variables
}
