package com.syswave.datos.common;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Properties;


/**
 *
 * @author Victor Manuel Bucio Vargas
 */
public abstract class ConfigurationManager
{
    /**
     * Obtiene los valores del archivo de propiedades de Conexion.
     * Nota: El tiempo promedio es de 0.3 segundos.
     * @param filePath Nombre del archivo.
     * @return Las propiedades contenidas en el archivo en cuestion.
     */
    public static Properties getConnectionProperties(String filePath)
    {
       //long start, end, res;
       //start = System.currentTimeMillis();
       File configuration = new File(filePath);
       /*end = System.currentTimeMillis();
       res = end - start;
       System.out.println("Referencia al archivo en: "+(res/1000.0) % 60 );*/
       Properties valuesSet = new Properties();
       String vendor = "mysql",     
              host = "localhost", 
              port = "3306",
              user = "root", 
              password = "1234", 
              schema = "miempresa";
       
       if (configuration.exists() && !configuration.isDirectory())
       {
           //start = System.currentTimeMillis();
           try (InputStream xmlInStream = new FileInputStream(configuration)) 
           {
              valuesSet.loadFromXML(xmlInStream);
              xmlInStream.close();
           }
       
           catch (IOException e) 
           {
               e.printStackTrace();
           }
            /*end = System.currentTimeMillis();
            res = end - start;
            System.out.println("Lectura al archivo en: "+(res/1000.0) % 60 );*/
       }
       
       else
       {
           try (OutputStream xmlOutStream = new FileOutputStream(configuration)) 
           {
             valuesSet.setProperty("vendor", vendor);
             valuesSet.setProperty("host", host);
             valuesSet.setProperty("port", port);
             valuesSet.setProperty("user", user);
             valuesSet.setProperty("password", password);
             valuesSet.setProperty("schema", schema);
             valuesSet.storeToXML(xmlOutStream, "This file will automatically generated by the system");
             
             xmlOutStream.close();
           }
       
           catch (IOException e) 
           {
                e.printStackTrace();
           }
       }
       
       return valuesSet;
    }
}